"""init

Revision ID: 0606bf440261
Revises: 4ed297789b99
Create Date: 2024-09-23 15:17:51.592594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0606bf440261'
down_revision = '4ed297789b99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
