"""init

Revision ID: 06fcaebdb8cb
Revises: 9401fd4d7972
Create Date: 2024-09-23 12:58:42.622670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06fcaebdb8cb'
down_revision = '9401fd4d7972'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
