"""init

Revision ID: 0893b2c34364
Revises: 2752945eb625
Create Date: 2024-09-23 12:21:08.939405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0893b2c34364'
down_revision = '2752945eb625'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
