"""init

Revision ID: 0935bf24f91f
Revises: 97f13fe58dfb
Create Date: 2024-09-23 16:22:58.018697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0935bf24f91f'
down_revision = '97f13fe58dfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
