"""init

Revision ID: 095e3cde6c2e
Revises: 125448e5eb69
Create Date: 2024-09-23 15:39:54.664679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '095e3cde6c2e'
down_revision = '125448e5eb69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
