"""init

Revision ID: 0a84cb8ef1fe
Revises: f4eacc87e335
Create Date: 2024-09-23 12:50:07.701088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a84cb8ef1fe'
down_revision = 'f4eacc87e335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
