"""init

Revision ID: 0b274b07de98
Revises: 1b34968ea27a
Create Date: 2024-09-23 16:06:22.914607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b274b07de98'
down_revision = '1b34968ea27a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
