"""init

Revision ID: 125448e5eb69
Revises: 8a3065305913
Create Date: 2024-09-23 15:39:51.373145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '125448e5eb69'
down_revision = '8a3065305913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
