"""init

Revision ID: 148a552e110c
Revises: 3215b3c5645b
Create Date: 2024-09-23 12:30:41.619632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '148a552e110c'
down_revision = '3215b3c5645b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
