"""init

Revision ID: 1861083740f0
Revises: 3490db6af2da
Create Date: 2024-09-23 12:44:00.837964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1861083740f0'
down_revision = '3490db6af2da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
