"""init

Revision ID: 18a8ff37099b
Revises: 4b41d19d9c81
Create Date: 2024-09-23 12:10:59.838447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18a8ff37099b'
down_revision = '4b41d19d9c81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
