"""init

Revision ID: 19c6b6944d48
Revises: 25b97f52bdb8
Create Date: 2024-09-23 18:34:44.455831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19c6b6944d48'
down_revision = '25b97f52bdb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
