"""init

Revision ID: 1acedc4d307c
Revises: 4643f7ac88d4
Create Date: 2024-09-23 12:32:45.254912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1acedc4d307c'
down_revision = '4643f7ac88d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
