"""init

Revision ID: 1b34968ea27a
Revises: b1c9a56506fc
Create Date: 2024-09-23 16:06:09.239463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b34968ea27a'
down_revision = 'b1c9a56506fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
