"""init

Revision ID: 1b3e4a83bfb2
Revises: 7ad52e671d14
Create Date: 2024-09-23 12:28:47.312551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b3e4a83bfb2'
down_revision = '7ad52e671d14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
