"""init

Revision ID: 1c750eec35c6
Revises: 148a552e110c
Create Date: 2024-09-23 12:31:29.139884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c750eec35c6'
down_revision = '148a552e110c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
