"""init

Revision ID: 1e09fd6df14f
Revises: 0606bf440261
Create Date: 2024-09-23 15:18:11.170038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e09fd6df14f'
down_revision = '0606bf440261'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
