"""init

Revision ID: 1ec5fc721a7c
Revises: db03bcd02e19
Create Date: 2024-09-23 12:10:09.715934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ec5fc721a7c'
down_revision = 'db03bcd02e19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
