"""init

Revision ID: 1f3cf7aed3b0
Revises: aaa902294386
Create Date: 2024-09-23 12:27:48.118686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f3cf7aed3b0'
down_revision = 'aaa902294386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
