"""init

Revision ID: 2021895f70db
Revises: 0b274b07de98
Create Date: 2024-09-23 16:08:36.592750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2021895f70db'
down_revision = '0b274b07de98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
