"""init

Revision ID: 2301d2e9b43d
Revises: 8306fd965cad
Create Date: 2024-09-23 12:18:30.279789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2301d2e9b43d'
down_revision = '8306fd965cad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
