"""init

Revision ID: 259023cb05dc
Revises: 4cd1b9c84251
Create Date: 2024-09-23 12:50:35.712266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '259023cb05dc'
down_revision = '4cd1b9c84251'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
