"""init

Revision ID: 25b97f52bdb8
Revises: 57cb98f5b3a0
Create Date: 2024-09-23 18:32:00.060101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25b97f52bdb8'
down_revision = '57cb98f5b3a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
