"""init

Revision ID: 2752945eb625
Revises: 2301d2e9b43d
Create Date: 2024-09-23 12:20:38.222173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2752945eb625'
down_revision = '2301d2e9b43d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
