"""init

Revision ID: 2c0acc685a6d
Revises: 4bd05594f1a4
Create Date: 2024-09-23 12:22:24.706798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c0acc685a6d'
down_revision = '4bd05594f1a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
