"""init

Revision ID: 2d51e348b3a8
Revises: 561a5a70c03a
Create Date: 2024-09-23 16:04:11.724746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d51e348b3a8'
down_revision = '561a5a70c03a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
