"""init

Revision ID: 3215b3c5645b
Revises: d66722998c89
Create Date: 2024-09-23 12:30:37.143203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3215b3c5645b'
down_revision = 'd66722998c89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
