"""init

Revision ID: 3490db6af2da
Revises: bcd5b5a29587
Create Date: 2024-09-23 12:37:38.410838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3490db6af2da'
down_revision = 'bcd5b5a29587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
