"""init

Revision ID: 3c2647eacebc
Revises: 1f3cf7aed3b0
Create Date: 2024-09-23 12:28:12.207563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c2647eacebc'
down_revision = '1f3cf7aed3b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
