"""init

Revision ID: 3c814869b4c9
Revises: 8ca74ef7014b
Create Date: 2024-09-23 20:56:40.616383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c814869b4c9'
down_revision = '8ca74ef7014b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
