"""init

Revision ID: 3e5c36da1a96
Revises: 900be6ca4220
Create Date: 2024-09-23 12:57:21.901385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e5c36da1a96'
down_revision = '900be6ca4220'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
