"""init

Revision ID: 420f8f9b3582
Revises: 56c2b53c6588
Create Date: 2024-09-23 12:16:53.390860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '420f8f9b3582'
down_revision = '56c2b53c6588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
