"""init

Revision ID: 4338cd379a6a
Revises: 18a8ff37099b
Create Date: 2024-09-23 12:11:14.270735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4338cd379a6a'
down_revision = '18a8ff37099b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
