"""init

Revision ID: 4643f7ac88d4
Revises: 3f817dee92a5
Create Date: 2024-09-23 12:32:23.053113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4643f7ac88d4'
down_revision = '3f817dee92a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
