"""init

Revision ID: 46b7f89d1d64
Revises: bca0be8667ad
Create Date: 2024-09-23 12:34:17.591438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46b7f89d1d64'
down_revision = 'bca0be8667ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
