"""init

Revision ID: 48030ffbe53d
Revises: 917c9c70f080
Create Date: 2024-09-23 15:40:46.775846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48030ffbe53d'
down_revision = '917c9c70f080'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
