"""init

Revision ID: 4ae1fc9abb14
Revises: a2559f471b90
Create Date: 2024-09-23 12:45:01.452966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ae1fc9abb14'
down_revision = 'a2559f471b90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
