"""init

Revision ID: 4b41d19d9c81
Revises: 1ec5fc721a7c
Create Date: 2024-09-23 12:10:33.606189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b41d19d9c81'
down_revision = '1ec5fc721a7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
