"""init

Revision ID: 4bd05594f1a4
Revises: 2fb067bf5e58
Create Date: 2024-09-23 12:22:10.560617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bd05594f1a4'
down_revision = '2fb067bf5e58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
