"""init

Revision ID: 4cd1b9c84251
Revises: 0a84cb8ef1fe
Create Date: 2024-09-23 12:50:33.016671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cd1b9c84251'
down_revision = '0a84cb8ef1fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
