"""init

Revision ID: 4ed297789b99
Revises: 9dc3076f9e1d
Create Date: 2024-09-23 15:17:13.432269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ed297789b99'
down_revision = '9dc3076f9e1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
