"""init

Revision ID: 50a984c5fb0d
Revises: 06fcaebdb8cb
Create Date: 2024-09-23 13:03:00.534419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50a984c5fb0d'
down_revision = '06fcaebdb8cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
