"""init

Revision ID: 561a5a70c03a
Revises: 34f6f649b6c5
Create Date: 2024-09-23 16:03:59.116877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '561a5a70c03a'
down_revision = '34f6f649b6c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
