"""init

Revision ID: 56c2b53c6588
Revises: 5d5716160b40
Create Date: 2024-09-23 12:15:17.372765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56c2b53c6588'
down_revision = '5d5716160b40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
