"""init

Revision ID: 57cb98f5b3a0
Revises: e1e0c9dbc2c1
Create Date: 2024-09-23 18:16:55.997526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57cb98f5b3a0'
down_revision = 'e1e0c9dbc2c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
