"""init

Revision ID: 5a5b0e3731fa
Revises: d372f781a8ae
Create Date: 2024-09-23 16:15:32.003177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a5b0e3731fa'
down_revision = 'd372f781a8ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
