"""init

Revision ID: 5c7b4e77f74e
Revises: 02187f70a003
Create Date: 2024-09-23 20:59:17.879134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c7b4e77f74e'
down_revision = '02187f70a003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
