"""init

Revision ID: 5d5716160b40
Revises: 355d25cd7d0c
Create Date: 2024-09-23 12:15:15.057588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d5716160b40'
down_revision = '355d25cd7d0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
