"""init

Revision ID: 60308def9123
Revises: 704caf706c7e
Create Date: 2024-09-23 12:07:42.237140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60308def9123'
down_revision = '704caf706c7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
