"""init

Revision ID: 61441578d888
Revises: 0893b2c34364
Create Date: 2024-09-23 12:21:18.686894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61441578d888'
down_revision = '0893b2c34364'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
