"""init

Revision ID: 63528aa9b310
Revises: 46b7f89d1d64
Create Date: 2024-09-23 12:34:22.010963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63528aa9b310'
down_revision = '46b7f89d1d64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
