"""init

Revision ID: 658561858698
Revises: a4a172b4a6c7
Create Date: 2024-09-23 16:10:17.314141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '658561858698'
down_revision = 'a4a172b4a6c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
