"""init

Revision ID: 66b8e74460a6
Revises: fdf2239d0ee5
Create Date: 2024-09-23 15:20:06.875398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66b8e74460a6'
down_revision = 'fdf2239d0ee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
