"""init

Revision ID: 6f9ed1bfe615
Revises: bae9771f30e4
Create Date: 2024-09-23 16:02:39.397620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f9ed1bfe615'
down_revision = 'bae9771f30e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
