"""init

Revision ID: 704caf706c7e
Revises: 757cdc9e8888
Create Date: 2024-09-23 12:07:35.501095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '704caf706c7e'
down_revision = '757cdc9e8888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
