"""init

Revision ID: 711eb85c8800
Revises: 61441578d888
Create Date: 2024-09-23 12:21:24.153872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '711eb85c8800'
down_revision = '61441578d888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
