"""init

Revision ID: 71c58db34cad
Revises: ef012f2548d1
Create Date: 2024-09-23 12:24:18.157400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71c58db34cad'
down_revision = 'ef012f2548d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
