"""init

Revision ID: 71d3ba403ad6
Revises: d60efce16d69
Create Date: 2024-09-23 11:59:12.319192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71d3ba403ad6'
down_revision = 'd60efce16d69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
