"""init

Revision ID: 74c704334080
Revises: 2c0acc685a6d
Create Date: 2024-09-23 12:22:29.241931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74c704334080'
down_revision = '2c0acc685a6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
