"""init

Revision ID: 757cdc9e8888
Revises: b5f8f0abccc3
Create Date: 2024-09-23 12:07:25.418570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '757cdc9e8888'
down_revision = 'b5f8f0abccc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
