"""init

Revision ID: 780ae081c7a6
Revises: 4338cd379a6a
Create Date: 2024-09-23 12:11:32.635350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '780ae081c7a6'
down_revision = '4338cd379a6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
