"""init

Revision ID: 7ad52e671d14
Revises: 3c2647eacebc
Create Date: 2024-09-23 12:28:37.552165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ad52e671d14'
down_revision = '3c2647eacebc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
