"""init

Revision ID: 7b331320d4cf
Revises: 8660b00a9ef3
Create Date: 2024-09-23 12:34:43.665159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b331320d4cf'
down_revision = '8660b00a9ef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
