"""init

Revision ID: 81d287b18566
Revises: 5c7b4e77f74e
Create Date: 2024-09-23 21:00:04.038729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81d287b18566'
down_revision = '5c7b4e77f74e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
