"""init

Revision ID: 8213d8930815
Revises: ce6c45068864
Create Date: 2024-09-23 12:27:13.128725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8213d8930815'
down_revision = 'ce6c45068864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
