"""init

Revision ID: 8306fd965cad
Revises: 95cb49964a7d
Create Date: 2024-09-23 12:18:27.946922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8306fd965cad'
down_revision = '95cb49964a7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
