"""init

Revision ID: 83e8877083b8
Revises: 1861083740f0
Create Date: 2024-09-23 12:44:16.807313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83e8877083b8'
down_revision = '1861083740f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
