"""init

Revision ID: 8660b00a9ef3
Revises: 63528aa9b310
Create Date: 2024-09-23 12:34:29.978255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8660b00a9ef3'
down_revision = '63528aa9b310'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
