"""init

Revision ID: 8aa088d11309
Revises: 50a984c5fb0d
Create Date: 2024-09-23 13:03:37.742599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aa088d11309'
down_revision = '50a984c5fb0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
