"""init

Revision ID: 8b2089a1cc81
Revises: 5a5b0e3731fa
Create Date: 2024-09-23 16:16:24.524925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b2089a1cc81'
down_revision = '5a5b0e3731fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
