"""init

Revision ID: 8ca74ef7014b
Revises: edeeab266500
Create Date: 2024-09-23 20:55:20.212253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ca74ef7014b'
down_revision = 'edeeab266500'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
