"""init

Revision ID: 8e197ce54cda
Revises: c3754b578c04
Create Date: 2024-09-23 21:03:29.881220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e197ce54cda'
down_revision = 'c3754b578c04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
