"""init

Revision ID: 8e7a3bdb490f
Revises: 0935bf24f91f
Create Date: 2024-09-23 16:24:00.091651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e7a3bdb490f'
down_revision = '0935bf24f91f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
