"""init

Revision ID: 900be6ca4220
Revises: 8332a03dd295
Create Date: 2024-09-23 12:55:27.201930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '900be6ca4220'
down_revision = '8332a03dd295'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
