"""init

Revision ID: 917c9c70f080
Revises: 095e3cde6c2e
Create Date: 2024-09-23 15:40:32.518902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '917c9c70f080'
down_revision = '095e3cde6c2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
