"""init

Revision ID: 921186d5502a
Revises: eb7d37a1fc70
Create Date: 2024-09-23 12:33:23.918611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '921186d5502a'
down_revision = 'eb7d37a1fc70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
