"""init

Revision ID: 9401fd4d7972
Revises: b344f5db6287
Create Date: 2024-09-23 12:57:43.815421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9401fd4d7972'
down_revision = 'b344f5db6287'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
