"""init

Revision ID: 95a13af6ed0e
Revises: 2021895f70db
Create Date: 2024-09-23 16:09:05.334327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95a13af6ed0e'
down_revision = '2021895f70db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
