"""init

Revision ID: 95cb49964a7d
Revises: adf016752313
Create Date: 2024-09-23 12:17:41.759014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95cb49964a7d'
down_revision = 'adf016752313'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
