"""init

Revision ID: 979b623e8864
Revises: 8aa088d11309
Create Date: 2024-09-23 13:03:57.031980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '979b623e8864'
down_revision = '8aa088d11309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
