"""init

Revision ID: 97f13fe58dfb
Revises: 8b2089a1cc81
Create Date: 2024-09-23 16:17:24.767918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97f13fe58dfb'
down_revision = '8b2089a1cc81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
