"""init

Revision ID: 9dc3076f9e1d
Revises: d346f58ce1bd
Create Date: 2024-09-23 15:16:54.117822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dc3076f9e1d'
down_revision = 'd346f58ce1bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
