"""init

Revision ID: a283b706ae7a
Revises: e91f7c0c6cea
Create Date: 2024-09-23 13:19:14.475740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a283b706ae7a'
down_revision = 'e91f7c0c6cea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
