"""init

Revision ID: a33ec1502fdf
Revises: f7336aefe331
Create Date: 2024-09-23 12:29:26.299963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a33ec1502fdf'
down_revision = 'f7336aefe331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
