"""init

Revision ID: a4a172b4a6c7
Revises: 95a13af6ed0e
Create Date: 2024-09-23 16:09:32.977554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4a172b4a6c7'
down_revision = '95a13af6ed0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
