"""init

Revision ID: b09b4ebe7a20
Revises: 1b3e4a83bfb2
Create Date: 2024-09-23 12:28:59.546075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b09b4ebe7a20'
down_revision = '1b3e4a83bfb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
