"""init

Revision ID: b1c9a56506fc
Revises: ee105b5b0d3c
Create Date: 2024-09-23 16:05:54.198874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1c9a56506fc'
down_revision = 'ee105b5b0d3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
