"""init

Revision ID: b344f5db6287
Revises: 3e5c36da1a96
Create Date: 2024-09-23 12:57:30.018153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b344f5db6287'
down_revision = '3e5c36da1a96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
