"""init

Revision ID: b5f8f0abccc3
Revises: 71d3ba403ad6
Create Date: 2024-09-23 11:59:14.696486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5f8f0abccc3'
down_revision = '71d3ba403ad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
