"""init

Revision ID: bae9771f30e4
Revises: 48030ffbe53d
Create Date: 2024-09-23 15:50:15.026975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bae9771f30e4'
down_revision = '48030ffbe53d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
