"""init

Revision ID: bca0be8667ad
Revises: c47676a6acbc
Create Date: 2024-09-23 12:34:06.151092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bca0be8667ad'
down_revision = 'c47676a6acbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
