"""init

Revision ID: bcd5b5a29587
Revises: f4103ae90311
Create Date: 2024-09-23 12:37:35.850846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcd5b5a29587'
down_revision = 'f4103ae90311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
