"""init

Revision ID: bd6e6bc3dfa7
Revises: 4ae1fc9abb14
Create Date: 2024-09-23 12:45:04.211058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd6e6bc3dfa7'
down_revision = '4ae1fc9abb14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
