"""init

Revision ID: c0f1daaa19c3
Revises: a33ec1502fdf
Create Date: 2024-09-23 12:30:19.271053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0f1daaa19c3'
down_revision = 'a33ec1502fdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
