"""init

Revision ID: c3754b578c04
Revises: e999caf2936f
Create Date: 2024-09-23 21:02:25.853743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3754b578c04'
down_revision = 'e999caf2936f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
