"""init

Revision ID: c47676a6acbc
Revises: 921186d5502a
Create Date: 2024-09-23 12:33:38.288707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c47676a6acbc'
down_revision = '921186d5502a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
