"""init

Revision ID: d0096826cfba
Revises: a283b706ae7a
Create Date: 2024-09-23 13:21:07.300378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0096826cfba'
down_revision = 'a283b706ae7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
