"""init

Revision ID: d0511c5d0797
Revises: 8e7a3bdb490f
Create Date: 2024-09-23 16:33:23.602404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0511c5d0797'
down_revision = '8e7a3bdb490f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
