"""init

Revision ID: d346f58ce1bd
Revises: eb3ae1f55c16
Create Date: 2024-09-23 15:16:19.326708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd346f58ce1bd'
down_revision = 'eb3ae1f55c16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
