"""init

Revision ID: d372f781a8ae
Revises: 96f923e289bd
Create Date: 2024-09-23 16:14:51.257932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd372f781a8ae'
down_revision = '96f923e289bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
