"""init

Revision ID: d5eecab3ac6f
Revises: 74c704334080
Create Date: 2024-09-23 12:22:33.696269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5eecab3ac6f'
down_revision = '74c704334080'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
