"""init

Revision ID: d66722998c89
Revises: c0f1daaa19c3
Create Date: 2024-09-23 12:30:28.092547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd66722998c89'
down_revision = 'c0f1daaa19c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
