"""init

Revision ID: dab600a26fe3
Revises: 71c58db34cad
Create Date: 2024-09-23 12:24:23.871437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dab600a26fe3'
down_revision = '71c58db34cad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
