"""init

Revision ID: db03bcd02e19
Revises: 60308def9123
Create Date: 2024-09-23 12:07:58.633777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db03bcd02e19'
down_revision = '60308def9123'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
