"""init

Revision ID: e1e0c9dbc2c1
Revises: d0511c5d0797
Create Date: 2024-09-23 16:34:15.307428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1e0c9dbc2c1'
down_revision = 'd0511c5d0797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
