"""init

Revision ID: e91f7c0c6cea
Revises: 979b623e8864
Create Date: 2024-09-23 13:04:16.104016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e91f7c0c6cea'
down_revision = '979b623e8864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
