"""init

Revision ID: e999caf2936f
Revises: 81d287b18566
Create Date: 2024-09-23 21:02:06.917771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e999caf2936f'
down_revision = '81d287b18566'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
