"""init

Revision ID: eb7d37a1fc70
Revises: 1acedc4d307c
Create Date: 2024-09-23 12:33:01.879815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb7d37a1fc70'
down_revision = '1acedc4d307c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
