"""init

Revision ID: edeeab266500
Revises: f260f8ee3dd8
Create Date: 2024-09-23 20:53:37.972471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edeeab266500'
down_revision = 'f260f8ee3dd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
