"""init

Revision ID: ee105b5b0d3c
Revises: 2d51e348b3a8
Create Date: 2024-09-23 16:05:37.397444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee105b5b0d3c'
down_revision = '2d51e348b3a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
