"""init

Revision ID: ef012f2548d1
Revises: d5eecab3ac6f
Create Date: 2024-09-23 12:22:41.662755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef012f2548d1'
down_revision = 'd5eecab3ac6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
