"""init

Revision ID: f260f8ee3dd8
Revises: 4d93b755a333
Create Date: 2024-09-23 18:54:32.125464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f260f8ee3dd8'
down_revision = '4d93b755a333'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
