"""init

Revision ID: f4eacc87e335
Revises: bd6e6bc3dfa7
Create Date: 2024-09-23 12:49:16.478528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4eacc87e335'
down_revision = 'bd6e6bc3dfa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
