"""init

Revision ID: f7336aefe331
Revises: b09b4ebe7a20
Create Date: 2024-09-23 12:29:13.163349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7336aefe331'
down_revision = 'b09b4ebe7a20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
