"""init

Revision ID: fdf2239d0ee5
Revises: 1e09fd6df14f
Create Date: 2024-09-23 15:19:55.000966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdf2239d0ee5'
down_revision = '1e09fd6df14f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
